name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: go vet
        run: go vet ./...

  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: go mod download
      - name: Unit test
        run: go test --tags=unit -v -cover -race ./...

  build:
    name: Build
    needs:
      - lint
      - unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: go-healthcheck:${{ github.sha }}
          build-args: |
            "BUILD_COMMIT=${{ github.sha }}"
      - name: Scan
        uses: Azure/container-scan@v0
        with:
          image-name: go-healthcheck:${{ github.sha }}
